""" endpoint constants """

ATTENDANCE = 'attendance'
AWARDS = 'awards'
CONFERENCE = 'conferences'
CONFIG = 'config'
DIVISION = 'divisions'
DRAFT = 'draft'
GAME = 'game'
GAME_PACE = 'gamePace'
HIGH_LOW = 'highLow'
HOMERUNDERBY = 'homeRunDerby'
JOBS = 'jobs'
LEAGUE = 'league'
META = 'meta'
PEOPLE = 'people'
SCHEDULE = 'schedule'
SEASON = 'seasons'
SPORTS = 'sports'
STANDINGS = 'standings'
STATS = 'stats'
TEAM = 'teams'
TRANSACTIONS = 'transactions'
VENUE = 'venues'
